### PR TITLE
Add support for subdirectories

### PR DESCRIPTION
**Pull request by gorlik**
Improvement to the file name translation
Support for subdirectories
Use stdint.h instead of custom types
renamed to DeskLink++

### CODE REVIEW

**Comment by gorlik** [comment]
thanks for the feedback.
The code is a work in progress but I wanted to send it to see if you were interested. 
please see my replies inline:

    *  
This is diff changes a lot at once, including mere style things, making it hard to figure out if anything that I value broke or changed behavior in a way that I consider broke. It will take me a bit to go through and test.
[GG] sorry about the indentation changes. My emacs is setup differently (i use 2 spaces and the original code seems to use 1 tab) and some code does not look quite right. I'll work on it but also feel free to correct it as well.

    
    *  
I don't think I want to change the name. I think it should just bump up to v2.0, and make the version more apparent, have it display in the output, start including the version when referencing it in directions and posts etc. Let that be the distiguisher. But I'll listen to argument if you think there is a more important reason to do it, like a different name would make it easier from the old dlplus which is still linked from club100 and bitchin100. All the old references don't specify any version number, so saying "dlplus 2" doesn't necessarily say to a new user that you didn't mean whatever dlplus they find. I may have just talked myself into it. ...no I haven't. I don't like "++" and "ng" etc. It's the same thing not a replacement, it's just been worked on and improved. It's v2.0
[GG] no problem. easy to change it back. I noticed even the major revision is tied to the github release. Was this on purpose?
    
    *  
Does it still build on at least mac and freebsd? I specifically value c for the portability. I'm not asking you to test that, I will test it. I'm just saying that it matters. To me anyway.
[GG] I have not tried. I have not used anything non POSIX but you never know.
    
    *  
Does the upcase option still work? It looks hard coded now.
[GG] I believe it works. I hardcoded the extension uppercasing to avoid my machine from crashing constantly when opening .do files (instead of .DO) 
    
    *  
I worry about unsafe assumptions when I see ts-dos filename, when there is really no such thing as a tsdos filename from the drive's point of view (even though this whole patch is about adding a ts-dos unique extension) ts-dos is just one of several clients that don't all behave the same. The disk emulator should serve all clients, and should make no assumptions that a real drive doesn't make.

There are exeptions but they are unavoidable and limited. For instance, the 6.2 vs 8.2 vs unformatted filenames. The only reason we have any knowledge about the 6.2 filenames is from the unavoidable discrepency that we are not storing the file data in raw space the way the real drives firmware is. The real drives firmware gets a 24 byte string from the client that looks like A _ _ _ _ _ . B A or A _ _ _ _ _ . B A _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ , and it stores that in a 24 byte chunk of raw disk space as A _ _ _ _ _ . B A _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _, and when the client later asks for a list of filenames, the drive sends back A _ _ _ _ _ . B A _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _. It doesn't care what's in any of the 24 bytes other than it does look at the 1st byte to see if it's a null. Only the 1st byte, if the the first is not null but all the rest are, it will regurgitate all 23 nulls back to the client. That's fine for the real drive but we want to store that as a file using a filename that's normal, so we want to collapse that to A.BA locally.

It's only because of that, that we are forced to have some knowledge of the client and make some kind of assumption about possibly reading A.BA from our disk but telling the client it's something else like that space-embedded-6.2-or-8.2-within-24 form. But that IS a broken assumption because "A.BA____..." is a perfectly legal filename to the drive, and it should be usable by any other clients just the same way it is on a real drive with a Z88 or Starlet or that Atari handheld that runs ms-dos. So those kinds of assumptions have to be as few as possible, and configurable not hard coded.

Or we could store the original name to return it later without making assumptions, but I don't think I want to deal with that. It would never be 100% and probably just be worse than doing nothing because of the inconsitency, when the file holding the original names is lost, or becomes out of sync with the actual contents of the directory, or when the file did not originally come from a M100 client and there is no original name etc... the behaviour would change vs other times when we did record an original filename and were able to retrieve it later.
[GG] good point. Perhaps we can make the file name conversion functions configurable at runtime. (currently it supports only 6.2 and 8.2 (both space filled) but this could be extended to 8.3 and raw)

     
    * For instance another unsafe assumption, adding the .DO extension when there is none on a local file. That's not technically a safe assumption even for the kc-85 clones let alone anyone else.
[GG] I imagined extension translation to be configurable as well. just didn't have any time to work on.
    

I'd be ok with an optional "Model T" mode that enables all kinds of KC-85-family-specific stuff like that though, and like what Laddie does with renaming between .BA and .DO automatically on the fly depending on what the contents look like, enfocing caps, limiting to the "legal" extensions, etc, maybe translate line-endings, add or remove the trailing Ctrl-Z, etc.
[GG] I wasn't thinking about advanced feature yet ;-) One feature I wanted to add though is the sardine dictionary access which is supported by the python TPDD server.

I probably did not need so much text to deliver each point but this way you can have something to criticize back :)

Anyway thanks much for this and I'll start checking it out. I have needed to do some work on this for a while. After making pdd.sh, I now have a better idea what it should do and how it should work than I did the last time I worked on it, so I think some things can be made a little more correct and solid and more universally compatible, just by knowing more about what the actual drive firmware does and doesn't do, what the drive does and doesn't care about, and which "rules" were actually just conventions implimented in clients and all we have to do is be dumb like the drive and that makes the emulator automatically less broken for everyone, even for random odd unknown rarely seen clients.
[GG] Unfortunately I don't have a TPDD. They are quite rare on ebay and usually ridiculously expensive.

thanks again for the feedback.
GG

**Comment by gorlik** [comment]
BTW: do you know that should be in the file type field in return block
type 0x11 (directory reference)?

**Comment by gorlik** [comment]
One more... what are the TS-DOS mistery commands?

**Comment by bkw777** [comment]
> BTW: do you know that should be in the file type field in return block type 0x11 (directory reference)?

File type? Do you mean the attribute byte?

Short answer: always write F in that field.

Long answer:
https://archive.org/details/tandy-service-manual-26-3808-s-software-manual-for-portable-disk-drive/page/24/mode/1up

An 0x11 response packet (return block) has this format:
| fmt    | len    | filename | attrib | size    | free   | cksum  |
|---|---|---|---|---|---|---|
| 1 byte | 1 byte | 24 bytes | 1 byte | 2 bytes | 1 byte | 1 byte |
| 0x11   | 0x1C   |          | F      |         | 0x80   |        |

fmt, len and cksum are about the packet itself, ie len is the length of the packet not the file, and is always 0x1C for this particular return type. It tells the client how many more bytes to read, which is how the drive can deliver binary data over serial, the drive and the client are always counting bytes.

free sectors we should just always write a dummy value that says the disk has 100% free space. No matter how many files we save, the client may always write another on this fake disk. I suppose we *could* fetch the actual free space of the filesystem of the directory dlplus is sharing, and actually write a real value there fs the free space actually does go below 100k !!!! That would actually be kinda fun just because why not? Or maybe calculate the % free of the real filesystem and say it's that many k free to the client.
PDDuino just returns 0x80 every time for 100% free space.
https://github.com/bkw777/PDDuino/blob/f84e9f40b17fac6276ef5b5643f82f5f5dae3c11/PDDuino/3_tpdd_commands.ino#L54

filename is any thing at all anywhere in the 24 bytes, with the only exception being a null in the first byte means no file.

attribute is almost irrelevant to the drive, but there is a convention that Floppy used, and so all other kc-85 clone clients that have to work like Floppy also do, and so we should emulate. The attribute field is just a text byte that can contain any letter, and it's just used as a search field when you ask for a file listing, you can specify this byte in a dirent() request (request block type 0x00, see the previous page to the manual page linked below) and the drive will show all files matching that attribute letter first. It's just a simple text match, and the drive still sends back all file entries, just it puts the matching ones first, if you specify any attribute in the request.

The convention we should emulate is just that all files have an F in that byte. Floppy always writes an F there when it saves a file, and so when the drive lists files there is always an F there for any files that Floppy created, and the drive itself blanks it to null when it deletes a file, and all the other clients that run on the kc-85 clones (TEENY, DSKMGR, TS-DOS, Disk Power, POWR-DISK, POWR-DOS) emulate Floppy. So for 99% of cases, the field is always F for any file or null for empty slots.

But it's actually not too important. I don't think anything is actually looking at it. All it seems to do is change the order that things appear in disk listings in the clients.

And technically, since it's purely a client convention, and we are supposed to be client agnostic, we should probably provide a way to do something else with that byte, in case some client actually does use it for something. I guess to be the most technically correct, we should record what the attribute byte has when a file is saved from a client, and reproduce it when sending back to a client, in case some other kind of client actually uses that byte for something real. And for cases where the file isn't originating from a client so you have to invent or presume some attribute, it could have a config option to default to always filling in either space (not null since there is a file of some sort) or F, or something else.

But realistically, we just pretend we read an F from our "disk" every time.
... and PDDuino is not doing that, but I'll update that now.
https://github.com/bkw777/PDDuino/blob/f84e9f40b17fac6276ef5b5643f82f5f5dae3c11/PDDuino/3_tpdd_commands.ino#L51

**Comment by bkw777** [comment]
> One more... what are the TS-DOS mistery commands?
> […](#)
> On Tue, 2022-05-17 at 21:42 -0700, Gabriele Gorla wrote: BTW: do you know that should be in the file type field in return block type 0x11 (directory reference)? On Tue, 2022-05-17 at 22:12 +0000, Gabriele Gorla wrote: > thanks for the feedback. > The code is a work in progress but I wanted to send it to see if > you > were interested. > please see my replies inline: > >     *   > This is diff changes a lot at once, including mere style things, > making it hard to figure out if anything that I value broke or > changed behavior in a way that I consider broke. It will take me a > bit to go through and test. > [GG] sorry about the indentation changes. My emacs is setup > differently (i use 2 spaces and the original code seems to use 1 > tab) > and some code does not look quite right. I'll work on it but also > feel free to correct it as well. > >      >     *   > I don't think I want to change the name. I think it should just > bump > up to v2.0, and make the version more apparent, have it display in > the output, start including the version when referencing it in > directions and posts etc. Let that be the distiguisher. But I'll > listen to argument if you think there is a more important reason to > do it, like a different name would make it easier from the old > dlplus > which is still linked from club100 and bitchin100. All the old > references don't specify any version number, so saying "dlplus 2" > doesn't necessarily say to a new user that you didn't mean whatever > dlplus they find. I may have just talked myself into it. ...no I > haven't. I don't like "++" and "ng" etc. It's the same thing not a > replacement, it's just been worked on and improved. It's v2.0 > [GG] no problem. easy to change it back. I noticed even the major > revision is tied to the github release. Was this on purpose? >      >     *   > Does it still build on at least mac and freebsd? I specifically > value > c for the portability. I'm not asking you to test that, I will test > it. I'm just saying that it matters. To me anyway. > [GG] I have not tried. I have not used anything non POSIX but you > never know. >      >     *   > Does the upcase option still work? It looks hard coded now. > [GG] I believe it works. I hardcoded the extension uppercasing to > avoid my machine from crashing constantly when opening .do files > (instead of .DO) >      >     *   > I worry about unsafe assumptions when I see ts-dos filename, when > there is really no such thing as a tsdos filename from the drive's > point of view (even though this whole patch is about adding a ts- > dos > unique extension) ts-dos is just one of several clients that don't > all behave the same. The disk emulator should serve all clients, > and > should make no assumptions that a real drive doesn't make. > > There are exeptions but they are unavoidable and limited. For > instance, the 6.2 vs 8.2 vs unformatted filenames. The only reason > we > have any knowledge about the 6.2 filenames is from the unavoidable > discrepency that we are not storing the file data in raw space the > way the real drives firmware is. The real drives firmware gets a 24 > byte string from the client that looks like A _ _ _ _ _ . B A or A > _ > _ _ _ _ . B A _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ , and it stores that > in > a 24 byte chunk of raw disk space as A _ _ _ _ _ . B A _ _ _ _ _ _ > _ > _ _ _ _ _ _ _ _ _, and when the client later asks for a list of > filenames, the drive sends back A _ _ _ _ _ . B A _ _ _ _ _ _ _ _ _ > _ > _ _ _ _ _ _. It doesn't care what's in any of the 24 bytes other > than > it does look at the 1st byte to see if it's a null. Only the 1st > byte, if the the first is not null but all the rest are, it will > regurgitate all 23 nulls back to the client. That's fine for the > real > drive but we want to store that as a file using a filename that's > normal, so we want to collapse that to A.BA locally. > > It's only because of that, that we are forced to have some > knowledge > of the client and make some kind of assumption about possibly > reading > A.BA from our disk but telling the client it's something else like > that space-embedded-6.2-or-8.2-within-24 form. But that IS a broken > assumption because "A.BA____..." is a perfectly legal filename to > the > drive, and it should be usable by any other clients just the same > way > it is on a real drive with a Z88 or Starlet or that Atari handheld > that runs ms-dos. So those kinds of assumptions have to be as few > as > possible, and configurable not hard coded. > > Or we could store the original name to return it later without > making > assumptions, but I don't think I want to deal with that. It would > never be 100% and probably just be worse than doing nothing because > of the inconsitency, when the file holding the original names is > lost, or becomes out of sync with the actual contents of the > directory, or when the file did not originally come from a M100 > client and there is no original name etc... the behaviour would > change vs other times when we did record an original filename and > were able to retrieve it later. > [GG] good point. Perhaps we can make the file name conversion > functions configurable at runtime. (currently it supports only 6.2 > and 8.2 (both space filled) but this could be extended to 8.3 and > raw) > >      >     * For instance another unsafe assumption, adding the .DO > extension when there is none on a local file. That's not > technically > a safe assumption even for the kc-85 clones let alone anyone else. > [GG] I imagined extension translation to be configurable as well. > just didn't have any time to work on. >      > > I'd be ok with an optional "Model T" mode that enables all kinds of > KC-85-family-specific stuff like that though, and like what Laddie > does with renaming between .BA and .DO automatically on the fly > depending on what the contents look like, enfocing caps, limiting > to > the "legal" extensions, etc, maybe translate line-endings, add or > remove the trailing Ctrl-Z, etc. > [GG] I wasn't thinking about advanced feature yet ;-) One feature I > wanted to add though is the sardine dictionary access which is > supported by the python TPDD server. > > I probably did not need so much text to deliver each point but this > way you can have something to criticize back :) > > Anyway thanks much for this and I'll start checking it out. I have > needed to do some work on this for a while. After making pdd.sh, I > now have a better idea what it should do and how it should work > than > I did the last time I worked on it, so I think some things can be > made a little more correct and solid and more universally > compatible, > just by knowing more about what the actual drive firmware does and > doesn't do, what the drive does and doesn't care about, and which > "rules" were actually just conventions implimented in clients and > all > we have to do is be dumb like the drive and that makes the emulator > automatically less broken for everyone, even for random odd unknown > rarely seen clients. > [GG] Unfortunately I don't have a TPDD. They are quite rare on ebay > and usually ridiculously expensive. > > thanks again for the feedback. > GG

No one knows. The only thing I ever saw about them was a couple years ago someone claimed to have observed a program on a NEC PC-8401 / PC-8500 use one:
Thread starts here:
https://www.mail-archive.com/m100@lists.bitchin100.com/msg12129.html
So they appear to be for TPDD2, but it's not documented anywhere.
I have figured out the TPDD2 sector access further than the document Ken Petit wrote up a long time ago, which is all implimented in github.com/bkw777/pdd.sh and I've still never seen it. However I do have both a PC-8401 and 8500 now so I could try out stardisk myself and collect a log of it's actions and find out at least a little more than that thread shows. For instance when Ken asked if the request was formatted normally, he never got the answer he meant. He meant, what was the request, aside from the first byte being 0x48, what did the rest of it look like? What did the drive respond with? The thread doesn't say but I could collect that now.

But for now it just means what the code says, you just recognize it enough to ignore it without error but otherwise ignore it. It will take a logging session with stardisk to actually figure out. Or some TPDD2 software manual that no one has turned up yet. All the tpdd2 commands we know about so far are the result of reverse engineering.

**Comment by bkw777** [comment]
While working on merging your changes, I half figured out one of the ts-dos mystery commands. 0x31 is a TPDD2-only command for writing to the cache ram on the drive. I know how to parse that command, and I had to copy it from a serial capture of a disk backup to make pdd.sh disk dump/restore work, but I still don't know exactly what the command does. That command has at least 2 modes where one mode writes data to a normal data part of the disk, and another mode seems to just be for metadata, and possibly for control.
I found the actual commands in the TS-DOS disassembly and verified that they are valid forms of that command.

TS-DOS has these canned strings used by the start-up routine. It's sending these commands and then apparently just checking to see if the response is a single byte of not?

```
4AE9H  DB    0x5A,0x5A,0x31,0x04,0x01,0x00,0x84,0xFF,0x46
4AF0H  DB    0x5A,0x5A,0x31,0x04,0x01,0x00,0x96,0x0F,0x24
4AF9H  DB    0x5A,0x5A,0x31,0x04,0x01,0x00,0x94,0x0F,0x26
```

For pdd.sh I had to clone two very similar commands from a log of a disk copy:
The two mystery/metadata writes here produce the same bytes as the first two lines above, except that 83 vs 84 on the first line.
The 3rd line above does not correlate to the 3rd line below. The 3rd line above is a 3rd metadat/msytery write, while the 3rd line below is writing ordinary payload data to a sector (well, just to cache, but it ends up in the data part of a sector on disk when it's flushed)
```
pdd2_flush_cache () {
	# mystery metadata writes
	pdd2_write_cache 01 00 83 || return $?
	pdd2_write_cache 01 00 96 || return $?
	# flush the cache to disk
	pdd2_sector_cache $1 $2 2 || return $?
}
```

The command breaks down like this:
```
0x5A  Z preamble 1/2
0x5A  Z preamble 2/2
0x31  REQ_CACHE_WRITE
0x04  4 bytes packet length
0x01    1/4: mode 1 (mystery/metadata/control, unknown function but does not write to the data part of a disk sector)
0x00    2/4: offset msb
0x84    3/4: offset lsb
0xFF    4/4: data (single byte of actual payload data)
0x46  checksum from 0x31 to 0xFF
```
That is a valid structure for that command. The pieces all fit. the 0x01 byte is a valid value in that spot, the 0x04 packet length checks out there are 4 bytes, and the checksum is correct, and, one line is actually identical to something the backup utility does, and the other is almost identical.

This is all just TPDD2. TPDD1 does not have this command.

So TS-DOS is tickling a function that only TPDD2 has, probably merely as  way to test for TPDD2. It might possibly do something else like configure the drive behavior in some way. I don't know what writing those bytes to those addresses in the drive cache with that mode 1 flag set actually does on a real drive.

References:
http://bitchin100.com/wiki/index.php?title=M100_TS-DOS_ROM_TPDD_Protocol
https://github.com/bkw777/pdd.sh/blob/41053c21f6f2ee349db2abf51547117de0a51b59/pdd.sh#L1637
https://trs80stuff.net/tpdd/tpdd2_boot_disk_backup_log_hex.txt

**Comment by gorlik** [comment]
Thanks for the detailed explanation.
BTW: I have fixed some of the issues with the formatting and started
working on some of the other comments. Feel free to get the latest git
to integrate the changes.

so far I ma thinking to have 3 operation modes:
1- ts-dos -> restrict to 6.2 (space padded)
2- wp-2 -> restrict to 8.2 (space padded)
3- raw -> restrict to 24 (free form - does it need space padding? )

Do we need a DOS mode with 8.3 as well?

Extension translation should be configurable and will be different for
each of the modes.
for #1:
always uppercase the extension (my machine keeps crashing when opening
the files with lowercase extensions)
.txt-> .DO
no ext -> .DO

any other useful combination?

I have no idea what to do for #2. And nothing to do for #3.

any suggestions?

thanks,
GG

**Comment by bkw777** [comment]
I was poking at it too. I'll hold off while you're active but one thing I think I figured out is the DME detection can be a lot simpler.
be_disk(), (which I've renamed to opr_scan() since all it really does now is scan for Operation-mode commands, in a very simple state-machine way.) I think really only needs to be this (untested pseudo-code with certainly bugs):
This is the entire thing now (again untested yet, treat as pseudo code)
```
// Scan tty for Operation-mode commands.
// Eat-and-discard bytes looking only for 2 consecutive Z's.
// On getting 2 Z's consecutive, try to read 2 more bytes.
// If success, try to read b[1]+1 more bytes.
// If success, dispatch b[] to cmd processor.
// Loop.
int opr_scan(void) {
	char* b[OPR_CMD_LEN+3] = { NULL };
	int z = 0;

	if(debug) fprintf(stderr,"opr_scan()\n");
		while (read(client_tty_fd, &b, 1) == 1) {
			if (z==2) {
				z=0;
				if (read(client_tty_fd, &b+1, 1) != 1) continue;
				if (b[1]>OPR_CMD_LEN) continue; // paranoia
				if (read(client_tty_fd, &b+2, b[1]+1) == b[1]+1) opr_dispatch(b);
				continue;
			}

			if (b[0]==0x5A) {
				z++;
				continue;
			}

			z=0;
		}
	return 0;
}
```
I don't know if that &b+2 syntax is correct yet, if not, it can just as easily keep overwriting b[] and store the seperate fields in their own variables, in simple ints, and just keep the payload as an array. check the cecksum on the spot, and just pass the cmd and the payload to the cmd dispatcher as two params. Also the data buffer above does not include the ZZ so checksum() is adjusted for that and all the other places that have like data[2] are changed to just data or data[0] etc.

Anyway setting aside the untested coding details...

The idea is like a little state-machine.

read a byte
have we seen 2 z's?
if yes, then the byte we just read was the cmd byte, reset z, process the rest of the command, reset the loop
if no, is the current byte a z?
if yes, increment z and loop
if no, reset z to 0 and loop.

That way, it eats non-Z bytes all day without caring what they are. Every time it gets a non-z, it resets the how-many-z's-have-I-seen counter. So if we get one Z but any other character next, we start over, and z only ever reaches 2 when they are consecutive. We don't issue any responses while scanning for Z and not getting one. We just eat and discard bytes until we see 2 Z consecutive, and we eat-and-discard those Z's themseves too. They don't make it into the payload buffer.

This is what a real drive does. We don't have to scan for M1 or keep track of anything that we read except the very byte we are one right now, and that simple state counter.

This takes care of most of the TS-DOS<>Desk-Link mutual detection scheme. TS-DOS sends a FDC-mode command that means "Switch to Operation mode", but it is an FDC-mode command sent when the drive is already in Operation-mode, and the FDC-mode command is meaningless junk to Operation-mode. This doesn't bother a real drive because a real drive is simply ignoring anything that isn't ZZ. The M1\r is ignored by a real drive. No error message, no effect on drive behavior. The reason for sending it in the first place is, the drive could have possibly been in FDC-mode, and if it was, this command would have put it into Operation-mode. So, after this point, the drive can be counted on to be in Operation-mode regardless what it was randomly before TS-DOS touched it.

Next TS-DOS sends an Operation-mode command to put the drive into FDC-mode.

Now the drive is in FDC-mode.

Finally TS-DOS sends a lone carriage-return, and checks to see how the drive responds to that.

That final 0x0D is what tells both TS-DOS and Desk-Link apart from a real drive or a non-TS-DOS client.

Neither the Operation-mode nore FDC-mode versions of the command to switch modes sends back any response. A real drive recognizes and acts on the command by switching modes, but doesn't say anything about it. It's just now waiting for a different set of commands.

FDC-mode commands begin with some command letter and are terminated by CR.
A real drive, in FDC-mode, when it gets that CR, will recognize it is a command terminator, but there was no command to process, so it does nothing. No error. It just goes back to the top of it's main loop waiting for a new command.

Desk-Link recognizes the sequence though and sends back a DME response. Also, the DME response is actually an invalid format that a real drive can never send. It's a 0x12 response, but with 11 bytes of payload instead of 1.

Desk-Link recognizes that it's talking to TS-DOS by this sequence, in particular the final lone 0x0D is the real proof that the previous two commands weren't legit normal commands sent by a client that really wanted to switch modes. Even if a client
was really using FDC-mode, it never has a reason to send a command terminator without a command.

TS-DOS recognizes that it's talking to Desk-Link by the fact that it gets a DME response, or gets nothing at all, or gets any other kind of response like a normal error. A real drive, if all went normally, would have sent nothing, and TS-DOS waits only 3ms after the 0x0D to see if it got anything back. A real drive, if anything was unusual like the drive wasn't in an expected state to begin with when the mode switch commands were send, will probably just send an ordinary error response by now. Either way, it wasn't the special illegal 11 byte 0x12 response.

Either way, whether TS-DOS gets a DME response or not, the next thing TS-DOS does is send the FDC-mode command to switch back to Operation-mode again. Remember at this point, a real drive would be sitting in FDC-mode. We are not a real drive and have no FDC-mode, but it doesn't matter. The main scan-for-zz routine will silently eat this command just like the first one.

All we have to do handle all this is,
1: The very simple scan-for-zz state machine. That takes care of both the initial and final FDC-mode commands that TS-DOS sends just naturally, simply because they are not ZZ and so they get thrown away like anything else that isn't ZZ. 
2: Recognize REQ_FDC just like any other command. We get ZZ, we read the length and checksum etc, and hand the collected command to the cmd dispatcher just like any other command.
3: in the cmd dispatcher, when we switch to case REQ_FDC, the zz scanner will have read the command up to and including the ckecksum. But honoring the length field, it will have stopped at the checksum and will NOT have consumed the trailing 0x0D. So now in the cmd disptatcher, in the switch case for REQ_FDC, we just try to read one byte from the tty. IF we get a byte, and IF that byte is 0x0D, then proceed with DME. Set an global to include dirs in dirent() calls, and immediately send a DME response.

in opr_dispatch():
```
	case REQ_FDC:
		if (!debug) fprintf(stderr,"REQ_FDC\n");
		/* Switch-to-FDC-mode only handled as part of
		TS-DOS<->Desk-Link mutual detection scheme to enable DME.

		It's a long story to explain the DME mutual-detection scheme
		accurately and completely. See ref/dme.txt

		The end result is:

		* The main loop should silently eat-and-discard anything that
		comes after any Operation-mode command and before the next ZZ.

		* Here (processing REQ_FDC) look for one more byte of input from
		the client. If there is a byte available, and it is 0x0D,
		then proceed with DME.
		*/
		if (read(client_tty_fd, &b, 1) == 1 && b==0x0D) send_current_path();
		break;
```
Also either right here or maybe in send_current_path() also set the global for dme support.

**Comment by bkw777** [comment]
One thing maybe not obvious, by the time z==2 passes, we will have just read a 3rd byte which is the cmd byte, so we only read one more byte to get the length not 2. then the rest of the command as normal.

**Comment by gorlik** [comment]
Thanks for the derailed explanation. Regarding the state machine, the way you describe is very close to how the original dlplus code works.
I changed to resemble the python tpdd emulator so it is possible to support sardine dictionary in the future. From reading the source seems it needs direct sector access.
Thanks,GG

Sent from Yahoo Mail on Android 
 
  On Thu, May 26, 2022 at 3:15, Brian K. ***@***.***> wrote:   


One thing maybe not obvious, by the time z==2 passes, we will have just read a 3rd byte which is the cmd byte, so we only read one more byte to get the length not 2. then the rest of the command as normal.

**Comment by bkw777** [comment]
Ah. That explains the R, R is the FDC-mode command for read sector.

That is interesting. That is the only example I've heard of any client actually using FDC-mode commands legitimately for their actual nominal purpose, not just as part of a trick like the DME detection. Operation-mode is used for everything else, and there are Operation-mode commands for sector access, so I wonder why they used the FDC-mode just for that?

Also, this means Sardine only works on TPDD1, because this is a TPDD1-only command.

Well that is one of the reasons I renamed that to opr_scan() and opr_dispatch() locally, looking ahead to adding fdc_scan() and fdc_dispatch() sometime. So this is a reason to go ahead and do it now as later.

FDC-mode commands are described in the software manual and in pdd.sh.
the FDC version of be_disk() / fdc_scan() would be a 
https://github.com/bkw777/pdd.sh/blob/41053c21f6f2ee349db2abf51547117de0a51b59/pdd.sh#L1130

FDC-mode, and any form of sector access in general, is really a whole seperate project. Without sector access, all normal Operation-mode commands translate more or less very simply to equivalent local file & filesystem actions. open/close/read/write/name/delete etc.

But sector access is a whole different thing that needs to deal with disk images, which means it needs controls and configs for disk image files.

I don't want to add that in a messy mixed-concernse way. Like how the current main loop has FDC commands mixed in with Operation commands, scanning for both ZZ and M1 R1 etc all at the same time. That's no good. It doesn't matter that mComm does it that way or that dlplus used to do it too, it was always wrong.

It's not only cleaner but easier and simpler, to emulate the drive by literally emulating the drive, be as stupid as it is, at least for some aspects. It's doing it's job in something like 2k of assembly so you know it is using very simple rules. The ZZ scanner must be nothing but a ZZ scanner, and the FDC scanner must be similar, a seperate routine that is switched over to and used instead. And that maps to the way the manual descibes how to use the commands. How there is a command to switch modes and then that's it, you are in that new mode and no longer in the other.

And managing disk images is yet another set of functionality that deserves it's own branch to work on. It's not a *huge* thing, but it's a complication and it doesn't need to happen all in the same patch with changing return (0) to return 0 and creating DMEReq and etc. Working as a raw disk with a disk image file is a totally different mode of operation than working as a file transfer util. I'd rather get the existing functions fixed up and improved, get the dme added, then as a seperat item, get a minimal stub version of fdc_scan() and fdc_dispatc() even if all they support is M and R and only even send back canned dummy response blocks, and then add sector access and disk images as a feature set of it's own.

**Comment by bkw777** [comment]
I think the dme sender should look more like this too. UNTESTED, and the checksum part isn't right for sure without some other changes because it's the entire 131 byte buf[], so it needs an intermediary array instead of writing directly to buf[] or something. But the point was there is no need for the dir_msg global. A dme response is just like any other Operation-mode response, and can use the same machinery. That's not the important part. The main thing is just sperating and simplifying the parts, getting rid of the canned root[] and just having a #define for the 6 visible bytes in plain text, and let the dme formatter & sender do the rest the same whether we're sending the root or a subdir.

```
void send_dme_ret(char *b) {
	int i;

	memset(buf,0x00,OPR_CMD_LEN+3);
	memset(buf,0x20,DME_LEN+2);

	buf[0]=RET_STD;
	buf[1]=DME_LEN;
	buf[2]=0x00;
	for(i=0; i<6 && b[i] ;i++) buf[3+i]=b[i];
	buf[9]='.';
	buf[10]='<';
	buf[11]='>';
	buf[12]=0x20;
	buf[13]=checksum(buf);  // FIXME

	my_write (client_tty_fd, buf, DME_LEN+3)
}

void send_current_path() {
	char t[PATH_MAX+1] = { NULL };
	char b = DME_ROOT;
	int i;
	int j;

	if (dir_depth>0) {
		getcwd(t,PATH_MAX)
		for(j=strlen(t); j>=0 ; j--) if(t[j]=='/') break;
		for(i=0; i<6 ;i++) b[i]=t[j+i];
	}

	send_dme_ret(b);
}
```

**Comment by gorlik** [comment]
The global is there to minimize the calls to getcwd as it is called
only when changing directories.
In any case it's not really an important optimization.

I think the one of the memset for buf is redundant.
The call to checksum is ok. The function knows how to look into the
buffer for the lenght of the packet and use just that.
send_current_path will not compile as written (send_dme_ret expects a
char * but b is a char) but I get the point.

thanks,
GG

**Comment by bkw777** [comment]
btw sorry I keep updating the comments with slightly better example code after the fact

**Comment by bkw777** [comment]
the 2nd memset for spaces is probably redundant but I didn't want to trust b[] not to have any nulls, but yeah every byte in the actual dme block is accounted for assuming b[] is ok, so really just the one for nulls.

**Comment by bkw777** [comment]
If the current dir gets sent multiple times when we know we have not changed, then I agree storing it is good. Which I guess it does, in fact probably *most* calls are unchanged, every time TS-DOS fetches a listing it gets that too. ok that goes back. Thanks.

**Comment by gorlik** [comment]
BTW: this is the python source I used as a reference
http://www.club100.org/memfiles/index.php?&direction=&order=&directory=Kurt%20McCullum/mComm%20Python







On Thursday, May 26, 2022, 08:25:00 PM PDT, Brian K. White ***@***.***> wrote: 







If the current dir gets sent multiple times when we know we have not changed, then I agree storing it is good. Which I guess it does, in fact probably most calls are unchanged, every time TS-DOS fetches a listing it gets that too. ok that goes back. Thanks.

**Comment by bkw777** [comment]
So now, something like this?

```
unsigned char dme_cwd[6] = DME_ROOT_LABEL;
...
void send_dme_cwd() {
	int i;

	memset(buf,0x00,OPR_CMD_LEN+3);

	buf[0]=RET_STD;
	buf[1]=RET_DME_LEN;
	buf[2]=0x00;
	for(i=0; i<6 ;i++) buf[3+i]=dme_cwd[i];
	buf[9]='.';
	buf[10]='<';
	buf[11]='>';
	buf[12]=0x20;
	buf[13]=checksum(buf);  // FIXME ?

	my_write (client_tty_fd, buf, RET_DME_LEN+3);
}

void update_dme_cwd() {
	char t[PATH_MAX+1] = { 0x00 };
	char b[6] = DME_ROOT_LABEL;
	int i;
	int j;

	if (dir_depth>0 && getcwd(t,PATH_MAX)) {
		for(j=strlen(t); j>=0 ; j--) if(t[j]=='/') break;
		for(i=0; i<6 ;i++)
			if(t[j+i]) b[i]=t[j+i];
			else b[i]=0x20;
	}

	for(i=0; i<6 ;i++) dme_cwd[i]=b[i];
}

```

open_file() calls update_dme_cwd()
opr_dispatch() REQ_FDC calls send_dme_cwd()

**Comment by bkw777** [comment]
I'm familliar with mComm

**Comment by bkw777** [comment]
Sardine is now working!

**Pull request merged**
